# Generated by Django 4.1.1 on 2022-09-29 21:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_remove_customer_phone'),
    ]

    operations = [
        migrations.CreateModel(
            name='AnimeContents',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, null=True)),
                ('image', models.FileField(max_length=200, null=True, upload_to='')),
                ('description', models.CharField(max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='AnimeInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('genre', models.CharField(max_length=200, null=True)),
                ('status', models.CharField(max_length=200, null=True)),
                ('rating', models.CharField(max_length=200, null=True)),
                ('reviews', models.CharField(max_length=200, null=True)),
                ('date_aired', models.DateField(max_length=200, null=True)),
                ('season', models.CharField(max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Settings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('darkmode', models.CharField(choices=[('darkmode', 'lightmode')], max_length=200, null=True)),
            ],
        ),
    ]
