# Generated by Django 4.1.1 on 2022-09-29 21:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_alter_settings_darkmode'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='AnimeContents',
            new_name='AnimeContent',
        ),
        migrations.AlterField(
            model_name='animeinfo',
            name='genre',
            field=models.CharField(choices=[('Horror', 'Horror'), ('Drama', 'Drama'), ('Fantasy', 'Fantasy'), ('Supernatural', 'Supernatural'), ('Tragedy', 'Tragedy')], max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='animeinfo',
            name='rating',
            field=models.CharField(choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5')], max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='animeinfo',
            name='status',
            field=models.CharField(choices=[('Still Airing', 'Still Airing'), ('Completed', 'Completed')], max_length=200, null=True),
        ),
    ]
