# Generated by Django 4.1.1 on 2022-09-30 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_delete_animecontent_animeinfo_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='animeinfo',
            name='genre',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
