# Generated by Django 4.1.1 on 2022-09-30 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_alter_animeinfo_genre'),
    ]

    operations = [
        migrations.AlterField(
            model_name='animeinfo',
            name='image',
            field=models.ImageField(max_length=200, null=True, upload_to=''),
        ),
    ]
