# Generated by Django 4.1.1 on 2022-10-05 21:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0015_alter_animeinfo_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='animeinfo',
            name='status',
            field=models.CharField(choices=[('0', 'Still Airing'), ('1', 'Completed')], default=0, max_length=20, null=True),
        ),
    ]
