# Generated by Django 4.1.1 on 2022-10-05 22:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0016_alter_animeinfo_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='animeinfo',
            name='rating',
            field=models.CharField(choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5')], default=None, max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name='animeinfo',
            name='status',
            field=models.CharField(choices=[('0', 'Still Airing'), ('1', 'Completed')], default=None, max_length=20, null=True),
        ),
    ]
