# Generated by Django 4.1.1 on 2022-10-07 01:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0017_alter_animeinfo_rating_alter_animeinfo_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='profile_pic',
            field=models.ImageField(blank=True, default='img-xiii.jpg', null=True, upload_to=''),
        ),
    ]
